/* Forge exercise how-to library.
   One entry per exercise name: s = setup, m = the motion (steps), c = cues & common mistakes. */
const EXERCISE_INFO = {

/* ================= LEGS — squat pattern ================= */
"DB Goblet Squat":{s:"Stand feet shoulder-width, toes slightly out, holding one DB vertically against your chest with both hands cupped under the top head.",m:["Brace your core and sit your hips down and back between your knees.","Keep the chest tall and heels planted until your thighs reach at least parallel.","Drive through the whole foot to stand, squeezing the glutes at the top."],c:["Push the knees out so your elbows track inside them.","Don't let the DB drift away from your chest.","Control 2–3s down, powerful up."]},
"DB Front Squat":{s:"Hold a DB on each shoulder, elbows lifted high, feet shoulder-width.",m:["Brace and squat straight down, keeping the torso as upright as possible.","Reach at least parallel, then drive up through mid-foot."],c:["Elbows stay high or the weight tips you forward.","Knees track over the toes, never caving in."]},
"DB Sumo Squat":{s:"Wide stance, toes out about 30°, one heavy DB hanging at arm's length between your legs.",m:["Sit straight down between the hips, torso tall.","Descend until the DB nears the floor or thighs hit parallel.","Stand by driving the knees out and squeezing the glutes."],c:["Shoulders stay stacked over hips — don't tip forward.","You should feel inner thighs and glutes."]},
"Heels-Elevated Goblet Squat":{s:"Heels on a 1–2 inch plate or board, DB held goblet-style at the chest.",m:["Squat straight down, letting the knees travel forward over the toes.","Go as deep as comfortable, then press up through the whole foot."],c:["The elevation shifts the work to the quads — stay upright and ride them.","Heels stay pressed into the plate the whole set."]},
"DB Box Squat":{s:"Stand just in front of a bench or box, DB held at the chest.",m:["Sit back until you touch the box lightly — don't relax onto it.","Pause a beat, then drive straight up without rocking."],c:["Touch, don't plop.","Shins near vertical; the hips do the work."]},
"Bodyweight Squat":{s:"Feet shoulder-width, toes slightly out, arms out front for balance.",m:["Sit the hips down and back, chest tall.","Reach parallel or below, then stand and squeeze the glutes."],c:["Heels stay down.","Knees push out, never caving in."]},
"Tempo Goblet Squat":{s:"Goblet squat setup with a lighter DB than usual.",m:["Lower for a strict 3-second count.","Pause 1s in the bottom, then stand fast."],c:["The slow descent IS the exercise — don't rush it.","Stay braced through the pause."]},
"Back Squat":{s:"Barbell across the upper traps, hands just outside the shoulders, feet shoulder-width.",m:["Big breath, brace, and sit the hips down and back.","Reach at least parallel, then drive up through mid-foot."],c:["Chest up, knees out.","Don't let the hips shoot up first out of the bottom."]},
"Front Squat":{s:"Barbell racked on the front delts, elbows high, fingertips under the bar.",m:["Squat straight down with a vertical torso.","Drive up, leading with the elbows."],c:["If the elbows drop, the bar dumps forward.","Full-foot pressure, heels down."]},
"Leg Press":{s:"Sit in the machine with feet shoulder-width, mid-platform.",m:["Lower under control until the knees near 90°.","Press through the whole foot without slamming the knees into lockout."],c:["Don't let the lower back roll off the pad at the bottom.","Full controlled range beats stacking plates."]},
"Leg Extension":{s:"Sit with the pad on the front of the ankles, knees lined up with the machine's pivot.",m:["Extend to a straight knee and squeeze the quads for 1s.","Lower slowly back to the start."],c:["No swinging or lifting the hips.","The slow lowering is half the work."]},
"Leg Curl":{s:"Set the pad just above the heels (lying or seated machine).",m:["Curl the heels toward the glutes.","Pause, then return slowly to a full stretch."],c:["Hips stay pinned to the pad.","Keep the toes pointed to make the hamstrings do it all."]},
"Walking Lunge":{s:"Open floor space, DBs at your sides (or bodyweight).",m:["Lunge forward and lower the back knee toward the floor.","Drive through the front heel and step straight into the next lunge."],c:["Tall torso; pause briefly between steps for balance.","Short, controlled strides — no crashing knees."]},
"Calf Raise":{s:"Balls of the feet on an edge or the flat floor, DB in one hand, other hand on support.",m:["Rise as high onto the toes as possible and squeeze for 1s.","Lower slowly into a deep stretch."],c:["Full stretch at the bottom, no bouncing.","Slow tempo beats big weight."]},

/* ================= LEGS — lunge / single-leg ================= */
"Bulgarian Split Squat":{s:"Rear foot laces-down on the bench, front foot 2–3 feet ahead, DBs at your sides.",m:["Drop the back knee straight down until the front thigh is parallel.","Drive through the front heel to stand."],c:["Slight forward lean = more glutes; upright = more quads.","Front knee tracks over the toes — don't let it dive inward."]},
"DB Reverse Lunge":{s:"Stand tall with DBs at your sides.",m:["Step one foot back and lower that knee straight down toward the floor.","Push through the FRONT heel to return to standing."],c:["Easier on the knees than forward lunges.","Torso tall — no pushing off the back foot."]},
"DB Forward Lunge":{s:"Stand tall with DBs at your sides.",m:["Step forward and lower the back knee toward the floor.","Push back off the front foot to the starting position."],c:["Front knee stays over the ankle, not past the toes.","Controlled steps, not falls."]},
"DB Step-Up":{s:"Bench or sturdy box around knee height, DBs at your sides.",m:["Plant the whole foot on the bench and drive through THAT heel to step up.","Lower back down slowly with the same leg doing the braking."],c:["Don't bounce off the floor leg — the top leg does all the work.","Stand fully tall at the top each rep."]},
"DB Split Squat":{s:"Staggered stance with both feet on the floor, DBs at your sides.",m:["Lower straight down until the back knee hovers just above the floor.","Drive up through the front heel; finish all reps, then switch legs."],c:["Keep the feet hip-width apart, not on a tightrope.","Straight down like an elevator, not forward."]},
"Curtsy Lunge":{s:"Stand tall, DB held at the chest or at your sides.",m:["Step one leg back and ACROSS behind the other, lowering the back knee.","Push through the front heel to stand."],c:["Hips stay square to the front.","You should feel the outer glute of the front leg."]},
"Reverse Lunge":{s:"Stand tall, hands on hips or clasped at the chest.",m:["Step back and drop the back knee straight down.","Drive through the front heel to stand."],c:["Torso tall, front shin near vertical.","Light fingertip support is fine while learning balance."]},

/* ================= LEGS — hinge / posterior ================= */
"DB Romanian Deadlift":{s:"Stand tall, DBs resting on the front of the thighs, knees soft.",m:["Push the hips straight back, sliding the DBs down the thighs and shins.","Stop when the hamstrings pull tight (around mid-shin), back flat.","Drive the hips forward to stand, squeezing the glutes."],c:["It's a hip hinge, not a squat — the knees barely bend more.","Lower slow (3s) and never round the back."]},
"DB Stiff-Leg Deadlift":{s:"Like an RDL but with nearly straight (not locked) knees.",m:["Hinge back with the DBs tracing the legs until a deep hamstring stretch.","Stand by driving the hips through."],c:["Range comes from hamstring flexibility, never the spine.","Flat back from start to finish."]},
"Single-Leg DB RDL":{s:"Stand on one leg with the DB in the OPPOSITE hand, standing knee soft.",m:["Hinge forward as the free leg extends straight back behind you.","Lower the DB toward mid-shin, hips staying level.","Squeeze the standing-leg glute to come back up."],c:["Hips square to the floor — don't let the top hip open up.","Tap the free toe down between reps if balance is shaky."]},
"DB Good Morning":{s:"Hold one DB vertically against the upper chest, feet hip-width, knees soft.",m:["Hinge at the hips until the torso nears parallel with the floor.","Squeeze the glutes to stand tall."],c:["Chest proud, back flat the whole way.","Hamstrings should be doing the talking, not the lower back."]},
"DB Sumo Deadlift":{s:"Wide stance, toes out, one heavy DB standing on end between your feet.",m:["Hinge down and grip the DB with both hands, chest up, back flat.","Stand by driving through the heels and pushing the knees out.","Hinge back down under control to set it down."],c:["The DB travels straight up and down, close to the body.","Re-brace before every pull."]},
"Bodyweight Hip Hinge":{s:"Feet hip-width, hands sliding down the front of the thighs.",m:["Push the hips straight back with soft knees and a flat back.","Feel the hamstring stretch, then squeeze the glutes to stand."],c:["Think 'close a car door with your butt'.","Grooves the pattern for every deadlift variation."]},
"Romanian Deadlift":{s:"Barbell at the thighs, overhand grip, knees soft.",m:["Hinge the hips back, bar sliding down the legs to mid-shin.","Drive the hips forward to stand."],c:["Bar stays glued to the legs.","Flat back — stop the descent where your hamstrings stop you."]},
"Deadlift":{s:"Barbell over mid-foot, grip just outside the legs, hips between knee and shoulder height.",m:["Brace, push the floor away, and stand up with the bar dragging up the legs.","Lock the hips at the top; hinge and bend to return it."],c:["The back stays flat — chest proud before every pull.","Push through the floor rather than yanking with the arms."]},

/* ================= LEGS — bridge / glutes ================= */
"Weighted Glute Bridge":{s:"Lie on your back, knees bent, feet flat near the glutes, DB resting across the hips (pad it with a towel).",m:["Drive through the heels and lift the hips until the body is straight from knees to shoulders.","Squeeze the glutes hard for 1s at the top, then lower with control."],c:["Ribs down — don't arch the lower back to fake extra height.","Push through the heels, not the toes."]},
"DB Hip Thrust":{s:"Upper back on the edge of the bench, feet flat, DB across the hips.",m:["Drive the hips up to a full lockout — shins vertical, body flat at the top.","Keep the chin tucked; lower until the hips near the floor."],c:["Squeeze 1–2s at lockout — that's the rep.","Don't hyperextend the lower back at the top."]},
"Single-Leg Glute Bridge":{s:"Glute-bridge setup with one leg extended straight or hugged to the chest.",m:["Drive the working heel down and lift the hips level.","Squeeze at the top, lower slow."],c:["Hips stay level like a tabletop — no tilting.","All the drive comes from the heel."]},
"Frog Pump":{s:"Lie on your back, soles of the feet pressed together, knees flopped out wide.",m:["Drive the outer edges of the feet down and pump the hips up.","Squeeze hard at the top; these work best at high reps."],c:["Short range, constant glute tension.","Chin tucked, ribs down."]},
"B-Stance Hip Thrust":{s:"Hip-thrust setup with one foot flat and the other resting heel-only, slightly ahead — about 70/30 loading.",m:["Thrust to lockout driving through the flat foot.","Keep the assisting leg light."],c:["A stepping stone toward full single-leg work.","Same lockout-and-squeeze rules as the two-leg version."]},

/* ================= CHEST — presses ================= */
"Flat DB Bench Press":{s:"Lie flat on the bench, feet planted, DBs at chest level just outside the shoulders.",m:["Press the DBs straight up until the arms lock out over the chest.","Lower for 2–3s until the elbows dip just below the bench line."],c:["Elbows about 45° from the torso — not flared to 90°.","Shoulder blades pinched beneath you for the whole set."]},
"Incline DB Press":{s:"Bench set to about 30°, DBs held at the upper chest.",m:["Press up and slightly back so the DBs finish over the upper chest.","Lower until you feel a stretch across the upper pecs."],c:["Don't turn it into a shoulder press — keep the arc over the chest.","Butt stays on the bench, feet planted."]},
"Incline Dumbbell Press":{s:"Bench set to about 30°, DBs held at the upper chest.",m:["Press up and slightly back so the DBs finish over the upper chest.","Lower until you feel a stretch across the upper pecs."],c:["Keep the arc over the chest, not the face.","Feet planted, no arching off the bench."]},
"Low-Incline DB Press":{s:"Bench at 15–20°, between flat and incline.",m:["Press over the upper chest; lower to a comfortable stretch."],c:["A shoulder-friendly middle ground — same rules as the flat press.","Control the negative."]},
"Incline DB Squeeze Press":{s:"30° incline, DBs pressed together over the chest, palms facing each other.",m:["Press up while squeezing the DBs into each other the entire rep.","Lower slowly without ever losing the inward pressure."],c:["The squeeze is the point — constant inner-chest tension.","Go lighter than a normal press."]},
"Incline Hex Press":{s:"Incline bench, hex DBs pressed flat against each other, palms in.",m:["Lower the pair to the chest with elbows tucked.","Press to lockout keeping the DBs glued together."],c:["Elbows stay close — inner chest and triceps do the work.","Smooth reps; the DBs never separate."]},
"Close-Grip DB Press":{s:"Lie on the bench with the DBs pressed together over the chest, palms facing each other.",m:["Lower the pair to the mid-chest with the elbows brushing the ribs.","Press to lockout, keeping the DBs squeezed together the whole rep."],c:["The tucked elbows and squeeze shift the work to triceps and inner chest.","Slow negative, no bounce off the chest."]},
"DB Floor Press":{s:"Lie on the floor, knees bent, DBs pressed over the chest.",m:["Lower until the triceps rest briefly on the floor.","Pause a beat, then press back to lockout."],c:["The floor shortens the range — great for pressing heavier safely.","No bouncing the elbows off the floor."]},
"Barbell Bench Press":{s:"Lie with eyes under the bar, feet planted, grip a bit wider than shoulders, blades pinched.",m:["Unrack and lower the bar to the mid-chest with elbows ~45°.","Press up and slightly back to lockout over the shoulders."],c:["Touch the chest under control — no bouncing.","Keep the wrists stacked over the elbows."]},
"Close-Grip Bench Press":{s:"Bench press setup with hands about shoulder-width apart.",m:["Lower the bar to the lower chest with elbows brushing the ribs.","Press to lockout, finishing with a triceps squeeze."],c:["A triceps move — the narrow grip and tucked elbows are the point.","Wrists straight, bar over the forearms."]},
"Push-Up":{s:"Hands under the shoulders, body in one straight line, core braced.",m:["Lower the chest to just above the floor, elbows about 45° from the body.","Press back up to straight arms."],c:["Hips neither sag nor pike.","Drop to the knees to scale down; elevate the feet to level up."]},
"Weighted Push-Up":{s:"Push-up position with a plate or light DB balanced between the shoulder blades.",m:["Perform a strict push-up — chest to the floor, press to lockout."],c:["Have your partner place and remove the weight.","Slow things down if the weight starts to shift."]},
"Wide-Grip Push-Up":{s:"Push-up position with the hands about 6 inches wider than the shoulders.",m:["Lower with the elbows tracking wider than usual, then press up."],c:["More chest, less triceps.","The range is shorter, so go all the way down."]},
"Feet-Elevated Push-Up":{s:"Feet up on the bench, hands on the floor under the shoulders.",m:["Lower the chest between the hands, then press back up."],c:["Hits the upper chest like an incline press.","Body rigid — don't let the hips drop."]},
"Close-Grip Push-Up":{s:"Hands directly under the shoulders or slightly closer, elbows tight.",m:["Lower with the elbows brushing the ribs, then press."],c:["A triceps builder — keep the elbows tucked.","Plank-rigid body the whole set."]},
"Dip":{s:"Support yourself on parallel bars (or two sturdy surfaces), arms locked.",m:["Bend the elbows and lower until the upper arms are about parallel.","Press back up to lockout."],c:["Slight forward lean hits chest; upright hits triceps.","Shoulders down away from the ears — don't sink."]},

/* ================= CHEST — flyes ================= */
"DB Bench Fly":{s:"Flat bench, DBs over the chest, palms facing, elbows softly bent.",m:["Open the arms in a wide arc until you feel a deep chest stretch.","Squeeze the DBs back together like hugging a barrel."],c:["The elbow angle never changes — it's a hug, not a press.","Go lighter than you think; the stretch is the stimulus."]},
"Incline DB Fly":{s:"30° incline bench, DBs over the upper chest, palms facing.",m:["Open the arms wide until the upper chest stretches.","Sweep back together over the chest."],c:["Soft, fixed elbow bend.","Slow on the way down — no dive-bombing."]},
"Floor DB Fly":{s:"Lie on the floor, DBs over the chest, palms facing, soft elbows.",m:["Open the arms until the upper arms lightly touch the floor.","Squeeze back together."],c:["The floor caps the stretch — a shoulder-safe fly.","Pause at the bottom, no bouncing."]},
"Cable Fly":{s:"Stand centered between cable stacks set at chest height, slight forward stagger.",m:["With soft elbows, sweep the handles together in front of the chest.","Squeeze 1s, then open with control to a full stretch."],c:["Constant tension — don't let the stack slam.","Shoulders stay back; arms hug, not press."]},
"Plate Svend Press":{s:"Stand tall, pressing a plate (or two small DB heads) flat between the palms at the chest.",m:["Push straight out to full arm extension while squeezing inward hard.","Pull back to the chest without losing the squeeze."],c:["The inward crush is the exercise.","High reps, big burn."]},

/* ================= BACK — rows & pulls ================= */
"One-Arm DB Row":{s:"Same-side knee and hand on the bench, other foot planted wide, DB hanging in the working hand, back flat.",m:["Pull the DB up and back toward the hip pocket.","Squeeze the shoulder blade 1s at the top.","Lower slowly to a full stretch."],c:["No torso twist — shoulders stay square to the floor.","Row to the hip, not the armpit."]},
"Chest Supported Row":{s:"Lie face-down on a 30–45° incline bench, DBs hanging straight under the shoulders.",m:["Row both DBs up and back with the elbows about 45° from the body.","Squeeze the blades together 1s, then lower to a dead hang."],c:["The bench removes all cheating — that's the point.","Chest stays glued to the pad."]},
"DB Bent-Over Row":{s:"Feet hip-width, hinge the torso to about 45°, DBs hanging, back flat.",m:["Row both DBs to the hips.","Lower under control without the torso bouncing."],c:["Hold the hinge like an RDL — if the back rounds, go lighter.","Elbows finish behind the ribs."]},
"DB Renegade Row":{s:"High plank with hands on the DB handles, feet set wide for a stable base.",m:["Row one DB to the hip while the other arm supports.","Lower it and switch sides, alternating."],c:["Hips stay square to the floor — the anti-rotation is the core work.","Use hex DBs so nothing rolls."]},
"Gorilla Row":{s:"Two DBs on the floor between your feet, wide stance, hinge down and hold both handles.",m:["Holding the hinge, row one DB to the hip while the other stays planted.","Set it down and row the other side."],c:["Back flat for the entire hold.","Push the floor away through the resting arm."]},
"Inverted Row":{s:"Bar or sturdy edge at waist height; hang beneath it with a straight body, heels on the floor.",m:["Pull the chest to the bar, squeezing the shoulder blades.","Lower to straight arms."],c:["Rigid body like a reverse plank.","Walk the feet forward to make it harder."]},
"Seal Row":{s:"Lie face-down flat along the bench (raise it on plates if the DBs touch down), DBs hanging.",m:["Row both DBs to the ribs and pause 1s.","Lower to a dead hang every rep."],c:["Zero momentum possible — pure lats and mid-back.","Let the blades protract fully at the bottom."]},
"Barbell Row":{s:"Hinge to about 45° over the bar, grip just outside the knees, back flat.",m:["Row the bar to the lower ribs.","Lower under control without standing up between reps."],c:["The torso angle holds still — no heaving.","Squeeze the blades at the top."]},
"Seated Cable Row":{s:"Seated at the cable stack, feet on the platform, knees soft, neutral grip.",m:["Pull the handle to the belly, driving the elbows back.","Let the arms and blades reach fully forward between reps."],c:["Tall chest; don't lean back to move big weight.","Full stretch, full squeeze."]},
"Pull-Up":{s:"Hang from the bar, hands just outside the shoulders, palms away.",m:["Pull the chin over the bar, driving the elbows down to the ribs.","Lower all the way to a dead hang."],c:["Start each rep by pulling the blades down before the arms bend.","Bands or slow negatives if full reps aren't there yet."]},
"Lat Pulldown":{s:"Seated at the stack, thighs under the pads, grip just outside shoulders.",m:["Pull the bar to the collarbones, elbows driving down.","Control the bar all the way back up."],c:["Chest tall with a slight lean back — no rocking.","Think 'elbows to hips', not 'hands to chest'."]},
"Face Pull":{s:"Rope on a high cable pulley, grip with palms facing in.",m:["Pull the rope toward your face, ends finishing beside the ears.","Let the arms reach fully forward between reps."],c:["Elbows high, hands pulled apart at the end.","Rear delts and upper back — keep it light and strict."]},
"Superman":{s:"Lie face-down, arms extended overhead, legs long.",m:["Lift the chest, arms and legs off the floor together.","Squeeze the whole backside 1s at the top, then lower slow."],c:["Lift with the glutes and mid-back, not by craning the neck.","Smooth reps, no flopping."]},

/* ================= BACK — traps ================= */
"DB Shrug":{s:"Stand tall with heavy DBs at your sides, arms straight.",m:["Lift the shoulders straight up toward the ears.","Pause 1s at the top, then lower into a full stretch."],c:["Straight up and down — no rolling the shoulders.","Long neck, chin level."]},
"Incline DB Shrug":{s:"Lie face-down on the incline bench, DBs hanging.",m:["Shrug the shoulder blades up and together without bending the elbows.","Pause, then let them stretch fully apart."],c:["Targets the mid-traps for posture.","Tiny range — the squeeze matters, not the distance."]},
"DB Upright Row":{s:"Stand with the DBs resting in front of the thighs, palms facing you.",m:["Pull the DBs up the body to lower-chest height, elbows leading and higher than the wrists.","Lower slowly."],c:["Stop at chest height — higher can pinch the shoulders.","Keep the DBs close to the body the whole path."]},
"DB High Pull":{s:"Slight hinge, DBs hanging at the knees.",m:["Explosively extend the hips and pull the elbows high, DBs reaching chest height.","Reset with control and repeat."],c:["Hips fire first, arms just finish the job.","It's a power move — crisp reps, no grinding."]},
"Farmer-Hold Shrug":{s:"Stand tall holding the heaviest DBs you can grip, at your sides.",m:["Shrug up and HOLD the top for 2s each rep.","Lower to a full stretch."],c:["Grip and traps together.","Stand tall, no forward lean."]},
/* ================= SHOULDERS — presses ================= */
"DB Overhead Press":{s:"Seated or standing, DBs at shoulder height, palms forward, core braced.",m:["Press straight up until the arms lock out overhead, biceps by the ears.","Lower under control back to the shoulders."],c:["Standing: squeeze the glutes so the lower back doesn't arch.","The DBs drift slightly toward each other at the top."]},
"Dumbbell Shoulder Press":{s:"Seated with back support, DBs at shoulder height, palms forward.",m:["Press to lockout overhead.","Lower until the DBs reach ear height or a touch lower."],c:["The backrest keeps it strict — no leg drive.","Don't clank the DBs at the top; finish just short of touching."]},
"Seated DB Shoulder Press":{s:"Seated upright on the bench (backrest up if you have one), DBs at the shoulders.",m:["Press both DBs to lockout overhead.","Lower with a 2s count to the shoulders."],c:["Ribs down, no slouching or arching.","Full lockout without shrugging the shoulders up."]},
"DB Push Press":{s:"Standing, DBs racked at the shoulders, feet hip-width.",m:["Dip the knees a few inches, keeping the torso upright.","Drive up hard through the legs and punch the DBs to lockout overhead.","Lower under control back to the shoulders."],c:["The dip is small and quick — it's a leg-powered press.","Brace before every rep."]},
"Arnold Press":{s:"DBs at the shoulders with the palms facing YOU.",m:["Press up while rotating the palms to face forward at the top.","Reverse the rotation on the way back down."],c:["One smooth corkscrew — hits all three delt heads.","Go lighter than your strict press."]},
"Single-Arm DB Press":{s:"Standing, one DB racked at the shoulder, free hand out or on the hip.",m:["Press to lockout without leaning away.","Lower with control; finish the set, then switch."],c:["The offset load makes your core fight — stay tall.","Squeeze the glutes to lock the body."]},
"Pike Push-Up":{s:"Hips high in a folded 'A' shape, hands shoulder-width, head between the hands.",m:["Bend the elbows and lower the crown of the head toward the floor.","Press back up to the pike."],c:["The more vertical the torso, the more shoulders it hits.","Elevate the feet on the bench to make it harder."]},
"Overhead Press":{s:"Barbell at the collarbones, grip just outside the shoulders, glutes squeezed.",m:["Press the bar straight up, pulling the head back out of the way.","Lock out overhead with the bar over mid-foot, then lower to the collarbones."],c:["Squeeze glutes and abs so the lower back doesn't arch.","The bar path is a straight vertical line."]},

/* ================= SHOULDERS — raises ================= */
"DB Lateral Raise":{s:"Stand tall, DBs at your sides, slight bend in the elbows.",m:["Raise the arms out to the sides up to shoulder height, leading with the elbows.","Lower for a slow 2–3s count."],c:["No swinging — if you're rocking, go lighter.","Tip the pinkies slightly up at the top, like pouring water."]},
"Lateral Raise":{s:"Stand tall, DBs at your sides, elbows softly bent.",m:["Raise out to shoulder height, elbows leading.","Lower slow — that half builds the delts."],c:["Shoulder height is plenty.","Strict form beats heavy weight here, always."]},
"DB Front Raise":{s:"DBs resting on the front of the thighs, palms down.",m:["Raise one or both arms straight in front to shoulder height.","Lower with control."],c:["No leaning back to heave the weight up.","Soft elbows, smooth arc."]},
"Leaning Lateral Raise":{s:"Grab the bench or rack with one hand and lean away from it, DB in the outside hand.",m:["Raise the DB out to shoulder height.","Lower slowly and repeat; switch sides."],c:["The lean keeps tension on the delt even at the bottom.","Same strict rules — no swinging."]},
"Seated Lateral Raise":{s:"Seated on the end of the bench, DBs hanging at your sides.",m:["Raise out to shoulder height, pause, lower slow."],c:["Sitting removes the body English entirely.","Lead with the elbows, not the hands."]},
"6-Way Shoulder Raise":{s:"Seated with light DBs hanging at your sides.",m:["Raise out to the sides → sweep to the front → raise up overhead.","Reverse the exact path back down. That's one rep."],c:["Go MUCH lighter than you think.","Every position is controlled — no momentum between stations."]},
"Rear Delt Fly":{s:"Hinge the torso to about 45°, DBs hanging below the chest, palms facing.",m:["Raise the arms out wide like wings, squeezing the rear delts.","Lower slowly without bouncing."],c:["Lead with the pinkies and keep the traps quiet.","Light weight, strict reps."]},

/* ================= ARMS — biceps ================= */
"DB Bicep Curl":{s:"Stand tall, DBs at your sides, palms facing forward.",m:["Curl the DBs to the shoulders with the elbows pinned to your ribs.","Lower for a slow 2–3s to full extension."],c:["No swinging hips or drifting elbows.","Full range beats heavy half-reps."]},
"Dumbbell Curl":{s:"Stand tall, DBs at your sides, palms forward.",m:["Curl to the shoulders, elbows pinned.","Lower slow to straight arms."],c:["Squeeze at the top for a beat.","If the elbows travel forward, the weight is too heavy."]},
"Barbell Curl":{s:"Stand tall holding the bar at shoulder-width, palms up.",m:["Curl the bar to the shoulders with the elbows glued to the ribs.","Lower for 2–3s to a full hang."],c:["No lean-back heave to start the rep.","Wrists stay straight."]},
"Hammer Curl":{s:"DBs at your sides with the palms facing each other.",m:["Curl to the shoulders keeping the neutral grip.","Lower slowly."],c:["Hits the brachialis and forearms for thicker arms.","Elbows pinned, no swinging."]},
"Incline DB Curl":{s:"Lie back on a 45–60° incline, arms hanging straight down behind the body line.",m:["Curl without letting the elbows drift forward.","Lower to a deep stretch."],c:["The stretched start position is the point — control it.","Head and shoulders stay on the bench."]},
"Concentration Curl":{s:"Seated, elbow braced against the inside of the thigh, DB hanging.",m:["Curl to the shoulder and squeeze 1s at the top.","Lower fully."],c:["The braced elbow makes cheating impossible.","Slow negatives make it twice as effective."]},
"Cross-Body Hammer Curl":{s:"DBs at your sides, palms facing in.",m:["Curl one DB across the body toward the opposite shoulder.","Lower and alternate arms."],c:["Keep the neutral grip the whole path.","Torso stays still — only the arm moves."]},
"Zottman Curl":{s:"DBs at your sides, palms forward.",m:["Curl up palms-up like a normal curl.","Rotate the palms to face DOWN at the top.","Lower slowly palms-down, then rotate back at the bottom."],c:["The slow palms-down lowering hammers the forearms.","Lighter than your normal curl weight."]},
"Spider Curl":{s:"Chest against the incline bench facing down, arms hanging straight toward the floor.",m:["Curl the DBs up with zero body movement.","Lower to a complete hang."],c:["Pure peak-contraction work.","Don't let the elbows swing back."]},

/* ================= ARMS — triceps ================= */
"Overhead DB Tricep Extension":{s:"Seated or standing, one DB held with both hands under its top head, pressed overhead.",m:["Lower it behind the head by bending ONLY the elbows.","Extend back to a full lockout."],c:["Elbows point forward, close to the ears — don't let them flare.","Ribs down; don't arch to finish reps."]},
"DB Skullcrusher":{s:"Lie on the bench, DBs pressed over the chest, palms facing each other.",m:["Bend at the elbows to lower the DBs beside the forehead/ears.","Extend back to lockout without the upper arms moving."],c:["Upper arms stay vertical and frozen — only the forearms hinge.","Keep the DBs on a path beside the head, not at the face."]},
"Skullcrusher":{s:"Lie on the bench holding the bar or DBs over the chest.",m:["Bend the elbows to lower the weight to the forehead line.","Extend back to lockout."],c:["Elbows in — flaring turns it into a press.","Slow negatives, no bouncing at the bottom."]},
"DB Kickback":{s:"Hinge forward, upper arm locked parallel to the floor along your side, DB hanging from a bent elbow.",m:["Extend the forearm back until the arm is completely straight.","Squeeze the triceps 1s, then lower just the forearm."],c:["The upper arm never drops — that's the whole exercise.","Light weight, perfect reps."]},
"Bench Dip":{s:"Hands on the bench edge behind you, fingers forward, legs extended out front.",m:["Bend the elbows to lower the hips toward the floor until the upper arms are near parallel.","Press back to straight arms."],c:["Shoulders stay down away from the ears.","Bend the knees to make it easier; elevate the feet to make it harder."]},
"DB Tate Press":{s:"Lie on the bench, DBs pressed over the chest, palms facing your feet.",m:["Bend the elbows OUT so the DB heads lower toward the middle of your chest.","Extend back up to lockout."],c:["An elbow-friendly triceps builder.","The DBs almost touch the chest each rep — full range."]},
"Tricep Pushdown":{s:"Cable at the top with a rope or bar, elbows pinned to your sides.",m:["Push the handle down to full lockout, splitting the rope at the bottom.","Let the forearms come all the way up without the elbows drifting."],c:["The elbows never leave your ribs.","Lean in slightly, but don't press with bodyweight."]},

/* ================= CORE — rotation / anti-rotation ================= */
"DB Anchored Russian Twist":{s:"Sit with the feet hooked under DBs or the bench, lean the torso back to 45°, DB held at the chest.",m:["Rotate the torso side to side, moving the DB across the body each way.","Each side counts toward the 'total'."],c:["Rotate from the ribs — don't just swing the arms.","Chest proud; don't round into a slouch."]},
"Russian Twist":{s:"Seated, heels lightly down or lifted, torso leaned back to 45°.",m:["Rotate side to side, hands or weight sweeping across.","Keep the tempo smooth and even."],c:["The shoulders turn, not just the arms.","Slower rotation = more core, less momentum."]},
"DB Plank Pull-Through":{s:"High plank, feet wider than the hips, one DB on the floor just outside one hand.",m:["Reach under the torso with the far hand and drag the DB across to the other side.","Alternate hands each rep."],c:["Hips stay level like a tabletop — fighting the tip IS the exercise.","Move the DB smoothly, no yanking."]},
"DB Wood Chop":{s:"Feet shoulder-width, hold one DB with both hands beside one hip.",m:["Swing it diagonally up and across the body to above the opposite shoulder, pivoting the back foot.","Control it back down along the same diagonal."],c:["Rotate through the hips and trunk together; the arms just hold on.","Smooth arcs — it's a chop, not a throw."]},
"Side Plank Reach-Through":{s:"Side plank on the forearm, feet stacked or staggered, top arm reaching to the ceiling.",m:["Thread the top arm under the torso, rotating slightly.","Sweep it back open to the ceiling."],c:["Hips stay lifted the entire set.","Follow the moving hand with your eyes."]},
"Bicycle Crunch":{s:"On your back, hands lightly behind the ears, legs lifted with knees at 90°.",m:["Bring one elbow toward the opposite knee while the other leg extends.","Alternate sides in a smooth pedal."],c:["Slow and smooth beats fast and sloppy.","Don't yank the neck — the elbow chases the knee via the ribs."]},
"DB Standing Twist":{s:"Stand with feet planted, light DB held at the chest with both hands.",m:["Rotate the torso side to side with control, hips mostly still.","Keep the DB close to the body."],c:["The resistance is small — make the control perfect.","Breathe out as you rotate."]},
"Cable Crunch":{s:"Kneel below a high cable with the rope held beside your head.",m:["Crunch the ribs down toward the pelvis, elbows sweeping toward the thighs.","Return until the abs reach a full stretch."],c:["The hips stay still — it's a spine curl, not a bow.","Abs move the weight, not the arms."]},

/* ================= CORE — anti-extension / lower abs ================= */
"DB 90-Degree Heel Tap":{s:"On your back, hips and knees bent to 90°, light DB pressed over the chest, lower back flat.",m:["Lower one heel to tap the floor while the DB stays over the chest.","Return and alternate legs."],c:["The lower back never leaves the floor — shorten the range if it does.","Exhale as the heel lowers."]},
"Dead Bug":{s:"On your back, arms reaching at the ceiling, hips and knees at 90°.",m:["Lower the RIGHT arm overhead and the LEFT leg toward the floor together, slowly.","Return and switch to the opposite pair."],c:["Back stays glued flat; exhale as the limbs lower.","Slow reps beat many reps."]},
"Hollow Body Hold":{s:"On your back, lower back pressed hard into the floor, arms overhead, legs long.",m:["Lift the shoulders and legs a few inches so the body forms a shallow banana.","Hold for the target time, breathing steadily."],c:["If the lower back arches up, bend the knees or raise the legs higher.","Squeeze the ribs toward the hips."]},
"Reverse Crunch":{s:"On your back, knees bent to the chest, hands by your sides.",m:["Curl the hips up off the floor, knees toward the chin.","Lower slowly without the feet touching down."],c:["Lift with the lower abs, not by rocking momentum.","Slow lowering is the best half of the rep."]},
"Lying Leg Raise":{s:"On your back, legs straight, hands beside the hips (or under them for support).",m:["Raise the legs to vertical with knees straight.","Lower slowly until just above the floor."],c:["Lower back stays down — bend the knees a little if it arches.","Don't let the heels rest between reps."]},
"Mountain Climbers":{s:"High plank, hands under the shoulders, hips low.",m:["Drive one knee toward the chest, then switch legs fast, like running in place."],c:["Hips stay down level with the shoulders.","Each knee drive counts toward the 'total'."]},
"Plank":{s:"Forearms down, elbows under the shoulders, body in one straight line.",m:["Brace the abs and squeeze the glutes; hold for the target time, breathing steadily."],c:["Hips neither sag nor pike.","Shaking is fine; sagging is a rep over."]},
"Hanging Leg Raise":{s:"Hang from the bar with straight arms.",m:["Raise the knees (harder: straight legs) up toward the chest.","Lower with total control, no swinging."],c:["Curl the pelvis up at the top — that's the abs.","Dead-stop each rep to kill momentum."]},

/* ================= ISOLATION ADDITIONS ================= */
"Incline-Bench DB Preacher Curl":{s:"Set the bench to roughly 45–60°. Stand or kneel behind it and press one upper arm firmly along the pad with a DB in that hand.",m:["Begin with the elbow nearly straight and the palm facing up.","Curl the DB toward the shoulder without lifting the upper arm from the bench.","Squeeze briefly, then lower slowly to a comfortable full stretch; finish the set before switching arms."],c:["The bench removes momentum — use less weight than a standing curl.","Stop before the elbow hyperextends or the shoulder rolls forward."]},
"DB Reverse Curl":{s:"Stand tall holding two light DBs at your sides with palms facing behind you and wrists straight.",m:["Curl both DBs toward the shoulders while keeping the palms down.","Pause without letting the wrists fold, then lower slowly to straight arms."],c:["Keep the elbows pinned beside the ribs.","Choose a lighter load than your normal curl; forearms and brachialis should lead."]},
"Rolling DB Triceps Extension":{s:"Lie on the bench holding two DBs over the shoulders with neutral palms and the upper arms angled slightly toward the head.",m:["Bend the elbows and lower the DBs beside the temples.","Let the upper arms roll back just enough for the DBs to travel behind the head.","Reverse the roll and extend the elbows to finish over the shoulders."],c:["The roll is small and controlled, not a pullover.","Keep the elbows from flaring wide."]},
"DB PJR Pullover":{s:"Lie lengthwise on the bench holding one DB by its inner head above the chest, elbows softly bent.",m:["Move the upper arms back and bend the elbows so the DB travels behind the head.","Feel the long head of the triceps stretch, then extend and sweep the DB back over the chest."],c:["Keep the ribs down and avoid turning it into a lower-back arch.","The elbows bend more than they would in a chest pullover."]},
"Seated DB Calf Raise":{s:"Sit near the edge of the bench with knees bent about 90°. Place the balls of both feet on a plate or block and rest one DB securely across the thighs just above the knees.",m:["Lower the heels into a controlled stretch.","Rise as high as possible onto the balls of the feet and hold for one second.","Lower slowly without bouncing."],c:["The bent knee emphasizes the soleus.","Keep the DB stable with both hands throughout the set."]},
"Reverse Nordic Curl":{s:"Kneel on a pad with knees about hip-width, torso upright, glutes tight, and hips fully extended.",m:["Keeping a straight line from knees through shoulders, lean the entire body backward from the knees.","Travel only as far as you can control, then drive the feet and shins into the floor to return upright."],c:["Do not sit the hips back toward the heels.","Begin with a short range; the quads should lengthen without sharp knee pain."]},
"Slider Hamstring Curl":{s:"Lie on your back with heels on sliders or folded towels over a smooth floor, knees bent, and hips lifted into a bridge.",m:["Slowly slide both heels away while keeping the hips off the floor.","Pull the heels back toward the glutes by squeezing the hamstrings.","Reset the bridge height before the next rep."],c:["Shorten the range if the hips drop or the lower back arches.","Use single-leg reps only after bilateral curls are controlled."]},
"Rack-Assisted Sissy Squat":{s:"Stand beside a rack upright and hold it lightly with one hand. Keep the feet close, rise onto the balls of the feet, and brace the glutes.",m:["Let the knees travel forward as the torso and thighs lean backward together.","Descend only as far as the quads can control while the body stays in one line.","Drive through the forefeet and straighten the knees to return."],c:["The rack is for balance, not for pulling yourself up.","Start shallow and stop if the knees feel sharp or unstable."]},
"Side-Lying Hip Abduction":{s:"Lie on one side with the bottom knee slightly bent, top leg straight, hips stacked, and top toes pointing forward.",m:["Brace the trunk and lift the top leg 12–18 inches without rolling the pelvis backward.","Pause while squeezing the outside glute, then lower slowly; finish the set before switching sides."],c:["Lead with the heel rather than turning the toes toward the ceiling.","A small strict range targets the glute better than a high swinging leg."]},
"Side-Lying DB External Rotation":{s:"Lie on one side holding a very light DB in the top hand. Bend that elbow to 90° and pin it against the ribs, forearm resting across the stomach.",m:["Keeping the elbow fixed, rotate the forearm upward until it points near the ceiling.","Pause briefly, then lower slowly across the stomach; finish the set before switching arms."],c:["Use a very light load and keep the shoulder stacked, not rolled backward.","The elbow stays glued to the ribs for every rep."]},
"Plate Pinch Hold":{s:"Stand over two smooth-sided plates or one bumper plate positioned on edge. Pinch securely with the fingers on one side and thumb on the other.",m:["Stand tall with the plate clear of the floor and hold for the target time.","Keep the wrist neutral, then squat or hinge to place the plate down under control."],c:["Keep the plates away from the feet in case the grip slips.","End the hold before the fingers begin to peel open."]},
"DB Wrist Curl":{s:"Sit on the bench holding two light DBs palms-up, forearms supported on the thighs with wrists just beyond the knees.",m:["Let the wrists extend under control, keeping the DBs secure in the palms.","Curl the knuckles upward using only the wrists, squeeze, and lower slowly."],c:["The forearms stay planted and the elbows do not curl.","Use a small controlled range rather than chasing heavy weight."]},
"DB Reverse Wrist Curl":{s:"Sit on the bench holding two very light DBs palms-down, forearms supported on the thighs with wrists just beyond the knees.",m:["Lower the knuckles slightly, then extend the wrists to lift the backs of the hands.","Pause at the top and return slowly without moving the elbows."],c:["This variation needs much less weight than a palm-up wrist curl.","Keep the movement smooth and the forearms fully supported."]},

/* ================= PULL-UP SKILL & GRIP ================= */
"Weighted Pull-Up":{s:"Secure added load with a dip belt or weighted vest, or carefully hold a light DB between the feet. Take a shoulder-width overhand grip and begin from a controlled hang.",m:["Pull the shoulder blades down, then drive the elbows toward the ribs.","Bring the chin over the bar without kicking or reaching the neck.","Lower to straight arms under control and reset before the next rep."],c:["Earn this progression with repeatable strict bodyweight pull-ups first.","Log only the added load, not bodyweight."]},
"Dead Hang":{s:"Use a secure pull-up bar. Step up to the bar, take a shoulder-width overhand grip, and let the feet clear the floor without jumping into the hang.",m:["Hang with long arms while keeping a light brace through the ribs and glutes.","Hold for the target time, then step back to the support instead of dropping."],c:["Keep the grip fully closed around the bar.","A passive stretch is fine, but stop if the front of the shoulder pinches."]},
"Scapular Pull-Up":{s:"Hang from the pull-up bar with straight elbows, hands just wider than shoulders, and feet clear of the floor.",m:["Without bending the elbows, pull the shoulder blades down so the body rises a few inches.","Pause briefly, then return slowly to a full hang."],c:["The elbows stay locked — this is a shoulder-blade motion.","Keep the ribs down instead of arching to create height."]},
"Assisted Pull-Up":{s:"Grip the pull-up bar and use a stable foot support or partner assistance that removes only as much bodyweight as needed.",m:["Pull the shoulder blades down, then drive the elbows toward the ribs.","Bring the chin over the bar and lower to straight arms under control."],c:["Use the least assistance that preserves a smooth full range.","Do not push so hard with the feet that the movement becomes a squat."]},
"Eccentric Pull-Up":{s:"Place a stable step beneath the pull-up bar. Step to the top position with the chin over the bar and take a secure grip.",m:["Remove the feet from the support and lower for a strict 3–5 seconds.","Reach a full hang, step back up, and reset for the next rep."],c:["Treat every lowering rep as its own controlled set-up.","Stop before the descent becomes a sudden drop."]},
"Hanging Knee Raise":{s:"Hang from the pull-up bar with straight arms, legs together, and the ribs lightly braced down.",m:["Curl the knees toward the chest while tipping the pelvis upward.","Pause without swinging, then lower slowly to a dead hang."],c:["Think pelvis toward ribs, not just knees toward hips.","Reset the swing before beginning the next rep."]},

/* ================= CARRIES, GRIP & LOWER LEG ================= */
"Farmer Carry":{s:"Clear a straight walking lane. Stand between two heavy DBs, hinge down with a flat back, and stand tall with one in each hand.",m:["Walk with short controlled steps, ribs stacked over the pelvis and shoulders level.","Turn carefully if needed, then hinge to set both DBs down under control."],c:["Do not rush as the grip tires.","Keep the DBs quiet at your sides instead of letting them swing."]},
"Suitcase Carry":{s:"Clear a walking lane and hold one DB at your side like a suitcase; keep the free hand relaxed and the shoulders level.",m:["Walk slowly without leaning toward or away from the DB.","Complete the distance or time, set it down under control, and switch sides."],c:["Stay tall as if balancing a glass on your head.","Shorten the set when the torso begins to drift sideways."]},
"Front-Rack Carry":{s:"Set the bar in the rack around upper-chest height, use collars, and clear a short walking lane. Hold the bar on the front delts with elbows high.",m:["Unrack, take short controlled steps, and keep the ribs stacked under the bar.","Walk the target time or distance, then return the bar squarely to both J-cups."],c:["Use a conservative load and never turn far away from the rack.","If the elbows drop or breathing cannot stay controlled, end the set."]},
"Barbell Static Hold":{s:"Set the bar in the rack just below lockout height with safety arms slightly lower. Load it evenly, use collars, and grip just outside the legs.",m:["Stand the bar up and hold tall with locked knees, long arms, and a firm brace.","After the target time, lower the bar directly back to the J-cups or safeties."],c:["This is a grip exercise, not a shrug or backbend.","Keep every rep inside the rack and stop before the hands begin to open."]},
"Standing Barbell Calf Raise":{s:"Set the bar at squat height inside the rack with safeties just below the shoulder position. Unrack it across the upper traps and stand with feet hip-width.",m:["Rise as high as possible onto the balls of the feet and pause for one second.","Lower the heels slowly to a complete stretch without bending the knees."],c:["Use the rack upright for orientation and keep the load conservative.","No bouncing — the pause and full stretch are the rep."]},
"Single-Leg DB Calf Raise":{s:"Stand on one foot near the rack or bench for light fingertip support, holding a DB in the opposite hand.",m:["Rise onto the ball of the working foot and squeeze at the top.","Lower the heel slowly to a full stretch; finish the set before switching."],c:["Use support for balance, not to pull yourself upward.","Keep the ankle tracking straight instead of rolling outward."]},
"Tibialis Raise":{s:"Stand with your back against a wall, feet about 8–12 inches forward, heels planted and knees softly bent.",m:["Lift the toes and forefeet toward the shins while the heels stay down.","Pause at the top, then lower slowly without resting completely."],c:["The front of the shins should do the work.","Move the feet closer to the wall to make it easier."]},

/* ================= SCAPULAR CONTROL & LATERAL CORE ================= */
"Chest-Supported Rear-Delt Row":{s:"Lie face-down on a 30–45° incline bench with light DBs hanging below the shoulders, palms facing the feet.",m:["Row with the elbows flared about 70–90° until the upper arms line up with the torso.","Squeeze across the rear shoulders, then lower to a full controlled hang."],c:["Use less weight than a normal row.","Keep the chest glued to the bench and the shoulders away from the ears."]},
"Prone Y-T-W Raise":{s:"Lie face-down on a low incline bench with bodyweight arms or very light DBs; keep the neck long and ribs supported.",m:["Raise the arms in a Y, lower; raise them out in a T, lower; then bend the elbows into a W and squeeze.","Move slowly through each position before beginning the next repetition."],c:["The shoulder blades move; the lower back stays quiet.","Use no weight if the upper traps take over or the shoulders pinch."]},
"Scapular Push-Up":{s:"Start in a high plank with hands under shoulders, elbows locked, and the body in one straight line.",m:["Let the chest sink a few inches as the shoulder blades glide together.","Push the floor away so the shoulder blades spread apart, without bending the elbows."],c:["Keep the body rigid — only the shoulder blades move.","Use an elevated bench position if the plank is difficult to control."]},
"Side Plank":{s:"Lie on one side with the elbow directly under the shoulder and legs stacked; bend the knees to make it easier.",m:["Lift the hips until the head, ribs, hips, and feet form one straight line.","Hold while breathing steadily, then lower under control and switch sides."],c:["Push the floor away and keep the bottom shoulder out of the ear.","Do not let the hips roll forward or sag toward the floor."]},

/* ================= BARBELL & RACK (Monster Lite additions) ================= */
"Barbell Hip Thrust":{s:"Upper back on the edge of the bench, bar rolled over the hips onto a pad or folded towel, feet flat.",m:["Brace, then drive the hips up to full lockout — shins vertical, body flat from knees to shoulders.","Squeeze the glutes 1–2s at the top with the chin tucked.","Lower under control until the plates nearly touch down."],c:["Full-size plates put the bar at the right height to roll on and off.","Ribs down at lockout — squeeze glutes, don't arch the lower back."]},
"Rack Pull":{s:"Set the safeties just below knee height and rest the loaded bar on them; stand at mid-foot, grip outside the legs.",m:["Hinge down to the bar, chest proud, back flat.","Push the floor away and stand to full lockout, bar dragging up the thighs.","Return the bar to the pins under control and reset each rep."],c:["A partial deadlift — you can overload it well beyond your floor pull.","Dead-stop every rep on the pins; no bouncing."]},
"Pendlay Row":{s:"Bar on the floor over mid-foot, hinge until the torso is parallel, grip just outside the knees.",m:["From a dead stop, row the bar explosively to the lower ribs.","Lower it all the way back to the floor and let it settle.","Re-brace and repeat — every rep starts from zero."],c:["The torso stays parallel; if you stand up as you pull, lighten it.","Dead-stop reps kill momentum — pure upper-back power."]},
"Chin-Up":{s:"Hang from the bar with palms facing YOU, hands about shoulder-width.",m:["Pull the shoulder blades down first, then drive the elbows to the ribs.","Chin over the bar, then lower to a full dead hang."],c:["The supinated grip brings biceps in hard — easier than pull-ups for most.","Scale with a band or slow 5-second negatives."]},
"Barbell Incline Press":{s:"Bench set to ~30° inside the rack, bar racked at arm's length; grip a bit wider than shoulders.",m:["Unrack and lower the bar to the upper chest, elbows ~45°.","Press up and slightly back to lockout over the shoulders."],c:["Set the safeties just below chest height when pressing alone.","Touch the upper chest, not the neck."]},
"Barbell Good Morning":{s:"Bar on the upper traps like a squat, feet hip-width, knees soft.",m:["Hinge at the hips until the torso approaches parallel, bar staying over mid-foot.","Squeeze the glutes and hamstrings to stand tall."],c:["Start light — this loads the hamstrings through a long lever.","Flat back always; range comes from the hips, not the spine."]},
"Barbell Reverse Lunge":{s:"Bar on the upper traps, feet hip-width, standing tall.",m:["Step one foot back and lower that knee straight down toward the floor.","Drive through the FRONT heel to return to standing; alternate or repeat one side."],c:["More knee-friendly than forward lunges under load.","Torso tall — don't tip forward as you step back."]},
"Barbell Shrug":{s:"Stand tall holding the bar at the thighs, hands just outside the legs.",m:["Lift the shoulders straight up toward the ears.","Pause 1s at the top, then lower into a full stretch."],c:["Straight up and down, no rolling.","The bar lets you load these heavy — keep the reps strict."]},
"Barbell Push Press":{s:"Bar racked at the collarbones, elbows slightly forward, feet hip-width.",m:["Dip the knees a few inches with a vertical torso.","Drive up hard through the legs and punch the bar to lockout overhead.","Lower under control back to the shoulders."],c:["The dip is quick and shallow — it's leg drive, not a squat.","Pull the head back so the bar travels straight."]},
"Barbell Rollout":{s:"Kneel on a pad, hands on the bar shoulder-width; round plates roll smoothly.",m:["Brace hard and roll the bar out, hips extending as the arms reach forward.","Go only as far as you can keep the back flat, then pull back with the abs."],c:["Shorter range beats a sagging lower back.","Exhale as you pull back in."]},

/* ================= CARDIO & MOBILITY ================= */
"Treadmill Run":{s:"Set an easy warm-up pace for 2–3 minutes before working pace.",m:["Run tall with a slight forward lean, quick light steps.","Log minutes in the reps field."],c:["Land under the hips, not out front.","A 1% incline mimics outdoor running."]},
"Rowing Machine":{s:"Feet strapped, shins vertical, arms long, back flat.",m:["Drive with the LEGS first, then swing the torso back, then pull the handle to the ribs.","Reverse the order on the way back: arms, torso, legs."],c:["Legs → back → arms; arms → back → legs.","Power comes from the push, not the pull."]},
"Cycling":{s:"Saddle height set so the knee stays slightly bent at the bottom of the stroke.",m:["Pedal in smooth circles at a steady cadence; log minutes in the reps field."],c:["Aim for a cadence around 80–90 rpm.","Light grip; shoulders relaxed."]},
"90/90 Hip Stretch":{s:"Sit with the front leg bent 90° in front of you and the back leg bent 90° out to the side.",m:["Sit tall, then hinge the chest forward over the front shin until you feel a deep outer-glute stretch.","Hold 30s, breathing slowly, then switch sides."],c:["Keep both sit bones heavy on the floor.","Ease in — stretch, don't strain."]},
};
